// Shared question definitions for display in admin dashboard
export const QUESTIONS: Record<number, string> = {
  1: "How often do you currently record video of yourself?",
  2: "Where do you usually show up on video (if at all)?",
  3: "How long have you been trying to show up on camera?",
  4: "When you think about recording today, you feel:",
  5: "How many videos do you actually publish per week?",
  6: "On average, how many takes does one video require before you're \"okay\" posting it?",
  7: "How long does one short video usually take from start to finish?",
  8: "What happens most often after you hit record?",
  9: "Watching your videos back usually feels:",
  10: "Do you feel like you're performing on camera?",
  11: "How connected do you feel to yourself on camera?",
  12: "When you make a mistake on camera, you usually:",
  13: "Which thought shows up most while recording?",
  14: "When filming feels the least intimidating, you imagine yourself:",
  15: "Which option feels most supportive right now?",
  16: "Your body feels safest on camera when you are:",
  17: "What feels more natural for you?",
  18: "Which type of video feels the most uncomfortable right now?",
  19: "Showing up on camera currently feels like:",
  20: "How consistent are you really with video?",
  21: "Which sounds most like your current situation?",
  22: "What's your biggest fear about showing up on camera?",
  23: "If nothing changed, what worries you most?",
  24: "What would help you most right now?",
  25: "How do you prefer to get unstuck?",
  26: "Right now, what are you most drawn to creating?",
  27: "Which feels most true right now?",
};
